
# Image
FROM continuumio/miniconda3 AS build

ARG version
ARG build_date

ENV PYTHONDONTWRITEBYTECODE=true
ENV PYTHONUNBUFFERED=true

# Labels
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=$build_date
LABEL org.label-schema.name="C-SCALE MQS"
LABEL org.label-schema.description="MQS is a package to search and identify Copernicus data across partners within the C-CALE data federation."
LABEL org.label-schema.url=""
LABEL org.label-schema.vcs-url=""
LABEL org.label-schema.vcs-ref=""
LABEL org.label-schema.vendor="EODC Gmbh (support@eodc.eu)"
LABEL org.label-schema.version=$version
LABEL org.label-schema.docker.cmd=""

# Add package
ADD . /mqs
WORKDIR /mqs

SHELL ["/bin/bash", "-c"]

# Create environment, install dependencies and package
RUN conda config --set always_yes yes && \
    conda config --append channels conda-forge && \
    conda update -n base -c conda-forge conda && \
    conda env create -f ./environment.yml && \
    source activate cscale-mqs && \
    pip install -e .[dev] && \
    conda deactivate && \
    conda install -c conda-forge conda-pack && \
    conda clean -ity

RUN echo "source activate cscale-mqs" > ~/.bashrc
ENV PATH="/opt/conda/envs/cscale-mqs/bin:$PATH"

# Make RUN commands use the cscale-mqs environment:
SHELL ["conda", "run", "-n", "cscale-mqs", "/bin/bash", "-c"]

