services:

  backend:
    ports:
      - 8000:8000
    volumes:
      - .:/mqs
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    environment:
      - APP_PORT=8000
      - APP_HOST=0.0.0.0
      - RELOAD=false
    restart: always
    command: bash -c "python -m mqs.app"

